UD-1648: update tags to define floating tag in addition to version
undistro/marvin pull request #63
Opened 2024-07-29 23:15 UTC by knrc

## Description
update the release workflow to include an additional floating tag based on the version's major/minor

## Linked Issues

## How has this been tested?

## Checklist
- [X] I have labeled this PR with the relevant [Type labels](https://github.com/undistro/.github/labels?q=Type%3A)
- [ ] I have documented my code (if applicable)
- [ ] My changes are covered by tests

2024-07-29 23:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/undistro/marvin?pullRequest=63) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/undistro/marvin?pullRequest=63) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/undistro/marvin?pullRequest=63) it.</sub>

2024-07-30 13:17 UTC, matheusfm requested changes

2024-07-30 13:17 UTC, matheusfm commented on .github/workflows/release.yml
> +            type=semver,pattern={{major}}.{{minor}}
Marvin images tags are currently prefixed with "v": `ghcr.io/undistro/marvin:v0.2.3`
This change would be changing this pattern.

2024-07-30 13:26 UTC, matheusfm requested changes

2024-07-30 13:26 UTC, matheusfm commented on .github/workflows/release.yml
> +            type=semver,pattern={{major}}.{{minor}}
```suggestion
          tags: |
            type=semver,prefix=v,pattern={{version}}
            type=semver,prefix=v,pattern={{major}}.{{minor}}
```

2024-07-30 15:13 UTC, matheusfm approved these changes

2024-07-30 15:17 UTC, knrc commented
I'll need to push up a new commit, the second commit isn't signed by github so we cannot merge

2024-07-30 16:17 UTC, knrc commented
Misread the warning, the commit had to be cryptographically signed.

2024-07-30 16:17 UTC, merged